package ru.itmo.tgbot.exception.user

class UserAlreadyExistsException(cause: Throwable): RuntimeException(cause)